### PR TITLE
Fix logit-laplace loss

### PR DESCRIPTION
**Pull request by thuangb**
This branch bring some fix to logit-laplace loss as clarified by the first author himself

### CODE REVIEW

**Comment by thuanz123** [comment]
Close this as in the Parti paper, author claim that logit-laplace loss harms the vit-vqgan training

**Comment by tachikoma777** [comment]
@thuanz123  this is information from the orig paper. I saw author  find that logit-laplace loss contributes to codebook usage. Do you mean logit-laplace is bad for FID so it should be turn off? Thanks!

**Comment by thuanz123** [comment]
Yeah in the original paper of [ViT-VQGAN](https://arxiv.org/abs/2110.04627), author claim that logit-laplace loss increase codebook usage but then in the [Parti ](https://arxiv.org/abs/2206.10789) paper claim that logit-laplace loss harm the quality of output iamge so they exclude this loss from training

**Comment by tachikoma777** [comment]
@thuanz123  thanks for providing this information!

**Pull request closed without merging**
